#!/bin/sh

IS_SNOW_LEOPARD=`/usr/bin/sw_vers -productVersion | grep 10.6`
PERL=/usr/bin/perl
if [ "$IS_SNOW_LEOPARD" != "" ] && [ -e "/usr/bin/perl5.8.9" ]
then
   PERL=/usr/bin/perl5.8.9
fi

APP_PATH=`dirname "$0"`
exec $PERL "$APP_PATH/bin/remedie-server.pl"
