#!/usr/bin/perl
use strict;
use warnings;
use LWP::UserAgent;
use HTTP::Request::Common;
use JSON::XS;

my $ua = LWP::UserAgent->new;
$ua->default_header('X-Remedie-Client' => 'CLI');

my $api_call = sub {
    my($method, $path, $args) = @_;
    my $uri = URI->new("http://localhost:10010/rpc$path");

    my $res;
    if ($method eq 'get' && $args) {
        $uri->query_form(%$args);
        $res = $ua->get($uri);
    } else {
        $res = $ua->$method($uri, $args);
    }

    return JSON::XS->new->decode($res->content);
};

my @channels = @ARGV ? get_channels(@ARGV) : all_channels();

for my $channel (@channels) {
    my $data = $api_call->("post", "/channel/refresh", { id => $channel->{id} });
    my $new = $data->{channel}{unwatched_count} - $channel->{unwatched_count};
    warn sprintf "%d: %s updated %s\n",
        $channel->{id}, $data->{channel}{name}, ($new ? "($new)" : "");
}

sub get_channels {
    my($ua, @ids) = @_;
    map $api_call->("get", "/channel/show", { id => $_ }), @ids;
}

sub all_channels {
    @{ $api_call->("get", "/channel/load")->{channels} };
}
