#!/usr/bin/perl
use strict;

my @deps;
sub requires {
    my($module, $ver) = @_;
    push @deps, $module;
}

open my $fh, "<", "Makefile.PL";
while (<$fh>) {
    /^\s*requires .*/ and eval $_;
}

system('cpan', '-i', @deps);

