#!/usr/bin/perl
use strict;
use YAML;

unless (-e "META.yml") {
    die "run perl Makefile.PL to generate META.yml\n";
}

my $meta = YAML::LoadFile("META.yml");
system('cpan', '-i', keys %{$meta->{requires}});
